const mongoose = require('mongoose');

const carSchema = new mongoose.Schema({
  brand: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'brand' 
    
  },
  carname:{type : String} ,
  
  salesranking: {type : String},
  launchedinput: {type : String},
  movrating: {type : String},
  heroimage: {type : String},
  heroimagename: {type : String},
  grayimage: {type : String},
  grayname: {type : String},
  bodytype: { type: String },
  subbodytype: { type: String },
  active: { type: String },
  redimage: {type : String},
  redname: {type : String},
  blueimage: {type : String},
  blueimagename: {type : String},
  blackimage: {type : String},
  blackimagename: {type : String},
  greenimage: {type : String},
  greenimagename:{type : String},
  creamimage: {type : String},
  creamimagename: {type : String},
  brownimage: {type : String},
  brownimagename: {type : String},
  yellowimage: {type : String},
  yellowimagename:{type : String},
  purpleimage: {type : String},
  purpleimagename: {type : String},
  whiteimage: {type : String},
  whitename:{type : String},
  seater:{type : String},
  fueltype:{type : String},
  transmissiontype:{type : String},
  NCAP:{type : String},
  upcoming : {type : String},
  itext : {type : String},
  carbrowsher : {type : String},
  pro: {type : String},
  cons: {type : String},
  asliheader1: {type : String},
  aslisummary1: {type : String},
  engineh1: {type : String},
  engineh2: {type : String},
  enginesummary1: {type : String},
  engineauto1: {type : String},
  engineimt1: {type : String},
  enginemanual1: {type : String},
  engineh2a: {type : String},
  engineh21: {type : String},
  enginesummary2: {type : String},
  engineauto2: {type : String},
  engineimt2: {type : String},
  enginemanual2: {type : String},
  engineh3: {type : String},
  engineh31: {type : String},
  enginesummary3: {type : String},
  engineauto3: {type : String},
  engineimt3: {type : String},
  enginemanual3: {type : String},
  engineh4: {type : String},
  engineh41: {type : String},
  enginesummary4: {type : String},
  engineauto4: {type : String},
  engineimt4: {type : String},
  enginemanual4: {type : String},
  standard: {type : String},
  extended: {type : String},
  Service: {type : String},
  keyF1: {type : String},
  keyF1text: {type : String},
  keyF2: {type : String},
  keyF2text: {type : String},
  keyF3: {type : String},
  keyF3text: {type : String},
  keyF4: {type : String},
  keyF4text: {type : String},
  keyF5: {type : String},
  keyF5text: {type : String},
  keyF6: {type : String},
  keyF6text: {type : String},
  keyF7: {type : String},
  keyF7text: {type : String},
  keyF8: {type : String},
  keyF8text: {type : String},
  keyF9: {type : String},
  keyF9text: {type : String},
  keyF10: {type : String},
  keyF10text: {type : String},
  keyF11: {type : String},
  keyF11text: {type : String},
  keyF12: {type : String},
  keyF12text: {type : String},
  keyF13: {type : String},
  keyF13text: {type : String},
  keyF14: {type : String},
  keyF14text: {type : String},
  keyF15: {type : String},
  keyF15text: {type : String},
  keyF16: {type : String},
  keyF16text: {type : String},
  keyF17: {type : String},
  keyF17text: {type : String},
  keyF18: {type : String},
  keyF18text: {type : String},
  keyF19: {type : String},
  keyF19text:{type : String},
  keyF20: {type : String},
  keyF20text:{type : String},
  spaceC1: {type : String},
  spaceC1text: {type : String},
  spaceC2: {type : String},
  spaceC2text: {type : String},
  spaceC3: {type : String},
  spaceC3text: {type : String},
  spaceC4: {type : String},
  spaceC4text: {type : String},
  popularity:{
    type: String,
    default:'null'
  },
  userRatingfromOwners:{
    type: String,
    default:'null'
  },
  spaceC5: {type : String},
  spaceC5text: {type : String},
  spaceC6: {type : String},
  spaceC6text: {type : String},
  spaceC7: {type : String},
  spaceC7text: {type : String},
  spaceC8: {type : String},
  spaceC8text: {type : String},
  spaceC9: {type : String},
  spaceC9text: {type : String},
  spaceC10: {type : String},
  spaceC10text: {type : String},
  spaceC11: {type : String},
  spaceC11text: {type : String},
  spaceC12: {type : String},
  spaceC12text: {type : String},
  spaceC13: {type : String},
  spaceC13text: {type : String},
  spaceC14: {type : String},
  spaceC14text: {type : String},
  spaceC15: {type : String},
  spaceC15text: {type : String},
  spaceC16: {type : String},
  spaceC16text: {type : String},
  spaceC17: {type : String},
  spaceC17text: {type : String},
  spaceC18: {type : String},
  spaceC18text: {type : String},
  spaceC19: {type : String},
  spaceC19text:{type : String},
  spaceC20: {type : String},
  spaceC20text:{type : String},
  storageC1: {type : String},
  storageC1text: {type : String},
  storageC2: {type : String},
  storageC2text: {type : String},
  storageC3: {type : String},
  storageC3text: {type : String},
  storageC4: {type : String},
  storageC4text: {type : String},
  storageC5: {type : String},
  storageC5text: {type : String},
  storageC6: {type : String},
  storageC6text: {type : String},
  storageC7: {type : String},
  storageC7text: {type : String},
  storageC8: {type : String},
  storageC8text: {type : String},
  storageC9: {type : String},
  storageC9text: {type : String},
  storageC10: {type : String},
  storageC10text: {type : String},
  storageC11: {type : String},
  storageC11text: {type : String},
  storageC12: {type : String},
  storageC12text: {type : String},
  storageC13: {type : String},
  storageC13text: {type : String},
  storageC14: {type : String},
  storageC14text: {type : String},
  storageC15: {type : String},
  storageC15text: {type : String},
  storageC16: {type : String},
  storageC16text: {type : String},
  storageC17: {type : String},
  storageC17text: {type : String},
  storageC18: {type : String},
  storageC18text: {type : String},
  storageC19: {type : String},
  storageCtext:{type : String},
  storageC20: {type : String},
  storageC20text:{type : String},

},{ timestamps: true });


module.exports = mongoose.model('Car', carSchema);

